### PR TITLE
fix: connection with dashmate local network

### PR DESCRIPTION
**Pull request by antouhou**
## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by shuplenkov — APPROVED** [review]

**Review by shumkov — APPROVED** [review]
👍

**Comment by thephez** [comment]
The title of this PR doesn't seem to match the changes it makes

**Comment by antouhou** [comment]
> The title of this PR doesn't seem to match the changes it makes

@thephez Yep, that PR updates DAPI client that has the changes that are related to the title. @shumkov insisted on that

**Comment by thephez** [comment]
> > The title of this PR doesn't seem to match the changes it makes
> 
> @thephez Yep, that PR updates DAPI client that has the changes that are related to the title. @shumkov insisted on that

Hmm, okay. That's not how we usually do it :thinking:

**Pull request merged**
