### PR TITLE
docs: getTransactions

### LINKED ISSUE #256: doc: getTransactionHistory returns empty array, should be getTransactions
https://dashevo.github.io/wallet-lib/#/account/getTransactionHistory

`getTransactionHistory` doesn't exist on type account, if account is cast to `any` it returns an empty array.

`getTransactions` exist on the type account and returns the transactions, but is not listed in the documentation.

### PR DESCRIPTION
**Pull request by dashameter**
closes #256

### CODE REVIEW

**Review by thephez — DISMISSED** [review]
LGTM :+1: I can't merge due to the semantic PR check below though.

**Comment by dashameter** [comment]
@thephez I changed the commit message shaving 5 chars off, hoping that will pass the Semantic Pull Request check, but no luck .. is there a way to skip it?

**Comment by thephez** [comment]
> @thephez I changed the commit message shaving 5 chars off, hoping that will pass the Semantic Pull Request check, but no luck .. is there a way to skip it?

Oh, I think you just needs to change `doc:...` to `docs:...`. That one trips me up sometimes.

**Review by thephez — APPROVED** [review]
Re-ACK

**Pull request merged**
